# Generated by Django 5.1.2 on 2025-01-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_customuser_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
